### ISSUE TITLE
Demo odin-control running on system

### ISSUE THREAD

**Issue by timcnicholls** [stfc-aeg/loki#22]

**Comment by josephnobes-stfc** [comment]
Odin-control has been demonstrated (recipe first added in 1f0975502e0bdd6983ee7f1e295e8cbdeac0749e) running the mercury-detector instance alongside odin-devices and odin-sequencer.

Odin-control version supported has been advanced to 1.2.0 (c7a348eb10152dd8e2fd09846677bb8dd5f684c4).
