### ISSUE TITLE
Create recipe for odin-sequencer

### ISSUE THREAD

**Issue by timcnicholls** [stfc-aeg/loki#8]

**Comment by josephnobes-stfc** [comment]
A recipe for odin-sequencer has now been added to the layer and build for PetaLinux.

As mentioned in 8ec350956386879aeb04a89885fb3df6b2455650, this required removal of pytest dependencies (which should not be needed outside of development) and inotify with a patch.

Inotify will not be needed to use raw sequencer functionality, but it would be useful to attempt to include it at a later date. This has been created as as separate issue (#12).
